CREATE DATABASE _COMPANY_;
USE _COMPANY_;

CREATE TABLE EMPL_OYEES(_EMP_ID INT PRIMARY key,_EMP_NAME VARCHAR(50),_DEPT_ID INT ,_SALARY_ INT);
CREATE TABLE DEPART_MENTS(_DEPT_ID INT,_DEPT_NAME VARCHAR(50));

INSERT INTO EMPL_OYEES(_EMP_ID,_EMP_NAME,_DEPT_ID,_SALARY_) value
(1, 'NELSON', 101, 100000),
(2, 'JON SNOW', 102, 90000),
(3, 'SCOUT', 103, 65000),
(4, 'JONATHAN', 104, 30000),
(5, 'NELSON', 101, 100000),
(6, 'MJ', 104, 75000),
(7, 'JON SNOW', 102, 90000),
(8, 'MEX', 105, 65000),
(9, 'SCOUT', 103, 65000),
(10, 'TOM', 103, 50000);


INSERT INTO DEPART_MENTS(_DEPT_ID,_DEPT_NAME) value
(101,'IT'),
(102,'HR'),
(103,'SALES'),
(104,'MARKETING'),
(105,'FINANCE');

ALTER TABLE EMPL_OYEES
ADD COLUMN HIRE_DATE DATE;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2026-08-10'
WHERE _EMP_ID =1;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2026-05-15'
WHERE _EMP_ID =2;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2025-12-20'
WHERE _EMP_ID =3;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2026-09-01'
WHERE _EMP_ID =4;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2026-04-10'
WHERE _EMP_ID =5;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2025-06-15'
WHERE _EMP_ID =6;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2026-07-25'
WHERE _EMP_ID =7;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2025-11-10'
WHERE _EMP_ID =8;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2026-02-28'
WHERE _EMP_ID =9;

UPDATE EMPL_OYEES
SET  HIRE_DATE ='2025-03-05'
WHERE _EMP_ID =10;

UPDATE EMPL_OYEES
SET  _SALARY_ = 90000
WHERE _EMP_ID =2;

UPDATE EMPL_OYEES
SET  _SALARY_ = 90000
WHERE _EMP_ID =3;

UPDATE EMPL_OYEES
SET  _SALARY_ = 90000
WHERE _EMP_ID =4;

SELECT * FROM EMPL_OYEES;
SELECT * FROM DEPART_MENTS;
DROP TABLE EMPL_OYEES;
#---------------------------------------------------------------------------------------
#9.1 Write query to find Nth highest salary
SELECT DISTINCT _EMP_NAME AS NAME,_SALARY_ AS SALARY FROM EMPL_OYEES
ORDER BY _SALARY_ DESC
LIMIT 1 OFFSET 1;

#---------------------------------------------------------------------------------------
#9.2 Remove duplicate records
SELECT DISTINCT D._DEPT_ID AS ID ,D._DEPT_NAME AS DEPARTMENT_NAME,E._EMP_NAME AS NAME 
FROM DEPART_MENTS AS D
JOIN EMPL_OYEES AS E
ON E._DEPT_ID = D._DEPT_ID;
#---------------------------------------------------------------------------------------
#9.3 Find records common in two tables
SELECT  D._DEPT_ID AS ID ,D._DEPT_NAME AS DEPARTMENT_NAME,E._EMP_NAME AS NAME 
FROM DEPART_MENTS AS D
INNER JOIN EMPL_OYEES AS E
ON E._DEPT_ID = D._DEPT_ID;
#---------------------------------------------------------------------------------------
#9.4 Find employees hired in last 6 months
SELECT * FROM EMPL_OYEES 
WHERE HIRE_DATE>= CURRENT_DATE - INTERVAL 6 MONTH;
#---------------------------------------------------------------------------------------
#9.5 Find continuous duplicate values

SELECT * FROM(SELECT _EMP_ID,_EMP_NAME,_SALARY_,
LAG(_SALARY_) OVER (ORDER BY _EMP_ID) AS PREVIOUS_SALARY 
FROM EMPL_OYEES) AS T
WHERE _SALARY_= PREVIOUS_SALARY;